import { NextResponse, type NextRequest } from "next/server";
import { getServerSupabase, getServerUser } from "@/lib/supabase-server";
import { getActiveTenant } from "@/lib/tenant";
import { computeLowStock } from "@/lib/low-stock";

/**
 * GET /api/purchase-proposal?format=csv|json
 * Tenant-scoped via session cookies → RLS.
 */
export async function GET(req: NextRequest) {
  const user = await getServerUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const format = req.nextUrl.searchParams.get("format") ?? "csv";
  if (format !== "csv" && format !== "json") {
    return NextResponse.json({ error: "format must be csv|json" }, { status: 400 });
  }

  const [sb, tenant] = await Promise.all([getServerSupabase(), getActiveTenant()]);
  if (!tenant) return NextResponse.json({ error: "No active tenant" }, { status: 400 });

  const { data: tenantRow } = await sb.from("gss_tenants").select("id").eq("prefix", tenant).maybeSingle();
  if (!tenantRow) return NextResponse.json({ error: "Tenant not found" }, { status: 404 });

  let items: Awaited<ReturnType<typeof computeLowStock>>;
  try { items = await computeLowStock(sb, tenantRow.id); }
  catch (e) { return NextResponse.json({ error: e instanceof Error ? e.message : String(e) }, { status: 500 }); }

  const generatedAt = new Date().toISOString();
  const timestamp   = generatedAt.replace(/[:.]/g, "-").slice(0, 19);
  const fname       = `gogrou-purchase-proposal-${tenant}-${timestamp}`;

  if (format === "json") {
    const payload = {
      _meta: {
        brand:           "Gogrou",
        document:        "Purchase Proposal",
        generated_at:    generatedAt,
        generated_by:    user.email ?? null,
        tenant_prefix:   tenant,
        source:          "https://gogrou.app",
      },
      items_count: items.length,
      items,
    };
    return new NextResponse(JSON.stringify(payload, null, 2), {
      headers: {
        "Content-Type":        "application/json; charset=utf-8",
        "Content-Disposition": `attachment; filename="${fname}.json"`,
      },
    });
  }

  // CSV — signature komentář na začátku
  const signature = [
    `# ========================================`,
    `# Gogrou — Purchase Proposal`,
    `# Tenant:        ${tenant}`,
    `# Generated:     ${generatedAt}`,
    `# Generated by:  ${user.email ?? "system"}`,
    `# Items:         ${items.length}`,
    `# Source:        https://gogrou.app`,
    `# ========================================`,
    ``,
  ].join("\r\n");

  const headers = [
    "GID","Type","Name","Manufacturer",
    "In stock","In machine","In service",
    "Min qty","Reorder point","Max qty",
    "Suggested qty","Reason",
  ];
  const rows = items.map((i) => [
    i.gid, i.type, i.name, i.manufacturer ?? "",
    i.in_stock_qty, i.in_production_qty, i.in_service_qty,
    i.min_qty ?? "", i.reorder_point ?? "", i.max_qty ?? "",
    i.suggested_qty, i.reason,
  ]);
  const csv = [headers, ...rows].map((row) =>
    row.map((cell) => {
      const s = String(cell ?? "");
      return /[,"\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    }).join(","),
  ).join("\r\n");

  return new NextResponse("﻿" + signature + csv, {
    headers: {
      "Content-Type":        "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${fname}.csv"`,
    },
  });
}
